openapi: 3.0.0
info:
  version: 0.1.0
  title: ENCRYPT API
  description: Specification of ENCRYPT APIs for exposing privacy-preserving computing service

servers:
  - url: https://${TBD}:${TBD}

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

paths:
  /dataowner/he/getcipher:  #CEA to define API for downloading a HE cipher tool
  /dataowner/he/dataupload: #CEA to define API for uploading data
  /dataowner/tee/verifier: #TRUSTUP
  /dataowner/preprocessor: #CERTH to define the api to download a preprocessing tool that for example will extract the meta information on data and provide them to ENCRYPT
  /dataowner/tee/attestation: #TRUSTUP
      post:
      description: Challenge Attestation against the ENCRYPT TEE
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - access_token
              properties:
                access_token:
                  type: string              
      responses:
        '200':
          description: Successfully inserted a new apikey or wallet address
          content:
            application/json:
              schema:
                type: object
                properties:   
                  code:
                    type: string
                  ra_quote:
                    type: string
        '401':
          description: Invalid Access Token
          content:
            application/json:
              schema:
                type: object
                properties:   
                  result:
                    type: string
                  reason:
                    type: string                      
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                type: object
                properties:   
                  result:
                    type: string
                  reason:
                    type: string  
  /dataowner/tee/dataupload: #TRUSTUP
  /dataowner/dp/dataupload: #8BELLS to define the upload of data for DP. Not sure if this makes sense. 
  /dataowner/recommendation/setreqs: #EXUS to define request to send for setting requirements of recommendation on data owner side
  /computation/status: #TRUSTUP
  /computation/start:  #TRUSTUP
  /researcher/recommendation/setreqs: #EXUS to define request to send for setting requirements of recommendation on researcher side
  
   
                    
 
